### ISSUE TITLE
Game crashes whenever i open or move items (armor) in my inventory

### ISSUE THREAD

**Issue by M3rl1nTH** [tr7zw/3d-Skin-Layers#208]
I attached a crash report below. I came here because Chat GPT pointed me to think your mod was causing the issue. I disabled it and sure enough the issue was gone. Don't know if it's strictly an issue on your part or an incompatibility with another mod. Hope this helps.
[crash-2024-12-09_22.06.58-client.txt](https://github.com/user-attachments/files/18067607/crash-2024-12-09_22.06.58-client.txt)

**Comment by tr7zw** [comment]
Update the mod, this has been fixed.

**Comment by M3rl1nTH** [comment]
I installed the mod yesterday form Modrinth, reinstalled it now and it's still crashing my game

**Comment by tr7zw** [comment]
The fixed version was released 2 days ago. You have ``skinlayers3d: 3d-Skin-Layers 1.7.3`` according to the log, you want 1.7.4: https://modrinth.com/mod/3dskinlayers/version/D4TLEY5I

**Comment by M3rl1nTH** [comment]
Here's an updated one on version which i believe is on v1.7.4[crash-2024-12-09_22.28.28-client.txt](https://github.com/user-attachments/files/18067737/crash-2024-12-09_22.28.28-client.txt)

**Comment by tr7zw** [comment]
> java.lang.NoSuchFieldError: Class net.minecraft.class_1723 does not have member field 'net.minecraft.class_2960 field_21668'
	at knot//net.minecraft.class_329.drawArmorHud(class_329.java:5743)
	at knot//net.minecraft.class_329.handler$doc000$ukus-armor-hud$renderArmorHud(class_329.java:5596)

Thats ``ukus-armor-hud: uku's Armor HUD 0.6.0+mc1.21.2`` crashing, because that mod is not made for 1.21.4.

**Comment by M3rl1nTH** [comment]
interesting, thank you for your help and sorry for wasting your time.

**Comment by tr7zw** [comment]
No problem. Always make sure everything is updated and matches the mc version/modloader. Using a launcher like the Modrinth launcher/Curseforge Launcher helps with that.
